### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by absyah** [absyah/inkode#7]

**Comment by absyah** [comment]
test hubot for @absyah

**Comment by danzcreation** [comment]
gini yak @absyah ?

**Comment by absyah** [comment]
test hubot for @absyah

**Comment by danzcreation** [comment]
hey @absyah

**Comment by absyah** [comment]
test @danzcreation

**Comment by absyah** [comment]
test lagi jon @danzcreation

**Comment by danzcreation** [comment]
@absyah gak ada apapun :laughing:

**Comment by absyah** [comment]
harus bisa @danzcreation

**Comment by absyah** [comment]
debug @danzcreation

**Comment by absyah** [comment]
debug @danzcreation

**Comment by absyah** [comment]
tanpa mention

**Comment by absyah** [comment]
tanpa mention

**Comment by absyah** [comment]
test dengan mendtion @danzcreation

**Comment by absyah** [comment]
ini ke ane doank @danzcreation

**Comment by absyah** [comment]
ini ke ane doank tanpa mention, harusnya kaga ada

**Comment by absyah** [comment]
ke personal @danzcreation

**Comment by absyah** [comment]
@danzcreation vs @absyah

**Comment by absyah** [comment]
@danzcreation @absyah 
Piye iki

**Comment by absyah** [comment]
@danzcreation @absyah  mumet

**Comment by absyah** [comment]
@danzcreation @absyah test

**Comment by absyah** [comment]
@danzcreation @absyah oke

**Comment by absyah** [comment]
test

**Comment by absyah** [comment]
@danzcreation @absyah how?

**Comment by absyah** [comment]
@danzcreation @absyah how? Syusyah

**Comment by absyah** [comment]
gimanuk @danzcreation @absyah

**Comment by absyah** [comment]
test harus bisa @danzcreation @absyah

**Comment by absyah** [comment]
debug @danzcreation @absyah
